#ifndef _INFRA_CONFIG_H_
#define _INFRA_CONFIG_H_

#define PLATFORM_HAS_STDINT
#define INFRA_STRING
#define INFRA_NET
#define INFRA_LIST
#define INFRA_TIMER
#define INFRA_SHA256
#define INFRA_REPORT
#define DEV_SIGN
#define MQTT_COMM_ENABLED
#define MQTT_DEFAULT_IMPL
#define ATM_ENABLED
#define AT_TCP_ENABLED
#define AT_PARSER_ENABLED
#define AT_TCP_HAL_SIM800

#endif
